version: '3'

services:
  nginx:
    image: nginx:1.18.0
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:50051
      - 443:443
    volumes:
      - ./conf/grpc_gateway.conf:/etc/nginx/conf.d/grpc_gateway.conf
      - ./conf/errors.grpc_conf:/etc/nginx/conf.d/errors.grpc_conf
      - ./ssl:/etc/ssl/

  rg1:
    image: afandy/routeguide:dev
    ports:
      - 10001:50051

  rg2:
    image: afandy/routeguide:dev
    ports:
      - 10002:50051
  rg3:
    image: afandy/routeguide:dev
    ports:
      - 10003:50051

  hw1:
    image: afandy/helloworld:dev
    ports:
      - 20001:50051
  hw2:
    image: afandy/helloworld:dev
    ports:
      - 20002:50051



