version: '3'

services:
  nginx:
    image: nginx:1.18.0
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:30051
      - 443:443
    volumes:
      - ./conf/grpc_gateway.conf:/etc/nginx/conf.d/grpc_gateway.conf
      - ./conf/errors.grpc_conf:/etc/nginx/conf.d/errors.grpc_conf
      - ./ssl:/etc/ssl/

  rg1:
    image: afandy/grpc-example-routeguide:latest
    ports:
      - 10001:50051

  rg2:
    image: afandy/grpc-example-routeguide:latest
    ports:
      - 10002:50051
  rg3:
    image: afandy/grpc-example-routeguide:latest
    ports:
      - 10003:50051

  hw1:
    image: afandy/grpc-example-helloworld:latest
    ports:
      - 20001:50051
  hw2:
    image: afandy/grpc-example-helloworld:latest
    ports:
      - 20002:50051

  haproxy:
    image: haproxy:1.9.2
    volumes:
        - "./conf/haproxy.sandy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    ports:
        - "81:3001"


